version: '3'
services:
  redis-cluster:
    container_name: redis-cluster
    environment:
     IP: 0.0.0.0
     SENTINEL: "false"
     STANDALONE: "false"
     INITIAL_PORT: 30001
     MASTERS: 3
    build:
      context: .
      args:
        redis_version: '5.0.7'
    hostname: server
    ports:
#      - '7000-7050:7000-7050'
      - '30001-30008:30001-30008'
      - '5000-5010:5000-5010'
  memcached:
    container_name: memcached
    image: memcached:latest
    ports:
      - "11211:11211"
  redis:
    container_name: redis
    image: redis:5.0.7
    ports:
      - "6379:6379"
    command: redis-server